config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  get 'search' => 'search#index'

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  mount_uploader :poster, MoviePosterUploader

  has_many :reviews
  validates :title,
    presence: true

  validates :director,
    presence: true

  validates :runtime_in_minutes,
    numericality: { only_integer: true }
  
  validates :description,
    presence: true

  # validates :poster_image_url,
  #   presence: true

  validates :release_date,
    presence: true

  def review_average
    if !reviews.empty?
      reviews.sum(:rating_out_of_ten)/reviews.size
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user,
    presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true }
  validates :rating_out_of_ten,
    numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
    numericality: { less_than_or_equal_to: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
serialize :roles, Array

has_many :reviews, dependent: :destroy
has_secure_password

validates :email,
  presence: true

validates :firstname,
  presence: true

validates :lastname,
  presence: true

validates :password,
  length: { in: 4..20 }, on: :create

def full_name
  "#{firstname} #{lastname}"
end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :restrict_admin_access
  before_filter :restrict_access

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.deleted_user_email(@user).deliver_now

    @user.destroy
    redirect_to admin_users_path
  end
  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def restrict_admin_access
    if current_user && !current_user.roles.include?("admin")
      flash[:alert] = "You are not an admin."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster, :description)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_movie
  before_filter :restrict_access

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

protected

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    title_or_director = params[:title_or_director]
    runtime = params[:runtime_in_minutes].to_i

    query = "(title like '#{params[:title_or_director]}%' or director like '#{params[:title_or_director]}%')"

    query += " and runtime_in_minutes < 90" if runtime < 90
    query += " and runtime_in_minutes >= 90 and runtime_in_minutes <= 120" if runtime >= 90 && runtime <= 120
    query += " and runtime_in_minutes > 120" if runtime > 120

    @movies = Movie.where(query)

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<h1>User List</h1>
<%= link_to "Back to main", movies_path %>

<% @users.each do |user| %>
  <p>name: <%= user.full_name %></p>
  <p>email: <%= user.email %></p>
  <%= link_to "Destroy", admin_user_path(user), method: :delete, data: {confirm: "You sure?"}, class: "btn btn-primary" %>
  <hr>
<% end %>

app/views/layouts/_admin_footer.html.erb
<% if current_user && current_user.roles && current_user.roles.include?("admin") %>
  <div>
    <%= link_to "Admin", admin_users_path %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", sessions_path, method: :delete %>)
    <% else %>
      <%= link_to "Log In", new_sessions_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<br>
<div class="container">
  <div class="well">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value) %>
    <% end %>
    
    <%= yield %>

    <%= render 'layouts/footer' %>
    <%= render 'layouts/admin_footer' %>
  </div>
</div>

</body>
</html>

app/views/movies/_form.html.erb
<% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for (@movie), :html => { :multipart => true } do |f| %>
  <div>
    <%= f.label "title" %><br>
    <%= f.text_field "title", class: "form-control" %>
  </div>
  <div>
    <%= f.label "release_date" %><br>
    <%= f.date_field "release_date", class: "form-control" %>
  </div>
  <div>
    <%= f.label "director" %><br>
    <%= f.text_field "director", class: "form-control" %>
  </div>
  <div>
    <%= f.label "runtime_in_minutes" %><br>
    <%= f.number_field "runtime_in_minutes", class: "form-control" %>
  </div>
  <div>
    <%= f.label "poster_image" %><br>
    <%= f.file_field "poster" %>
  </div>
  <div>
    <%= f.label "description" %><br>
    <%= f.text_area "description", class: "form-control" %>
  </div>
  <div>
    <br>
    <%= f.submit "Submit", class: "btn btn-primary" %> 
  </div>
<% end %>

app/views/movies/_movie.html.erb
<% @movies.each do |movie| %>
  <%= link_to image_tag(movie.poster), movie_path(movie) %>
  
  <h2><%= link_to movie.title, movie_path(movie) %></h2>
  
  <h3><%= formatted_date(movie.release_date) %></h3>
  
  <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
  
  <p><%= movie.description %></p>
  <hr>
<% end %>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Submit a movie!", new_movie_path %>
<hr>

<h3>Search For A Movie</h3>
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:title_or_director, "Search by title or director:") %>
  <br>
  <%= text_field_tag :title_or_director %>
  <br>
  <br>
  <%= label_tag(:runtime_in_minutes, "Runtime:") %>
  <br>
  <select name="runtime_in_minutes">
    <option value="89">Under 90 minutes</option>
    <option value="90">Between 90 and 120 minutes</option>
    <option value="121">Over 120 minutes</option>
  </select>
  <br>
  <br>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>
<hr>

<%= render 'movie' %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %>
<br>

<%= link_to image_tag(@movie.poster), movie_path(@movie) %>

<h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>

<h3><%= formatted_date(@movie.release_date) %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>

<p><%= @movie.description %></p>
<p>Average Score: <%= @movie.review_average %>/10</p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>Reviewer: <%= review.user.full_name %></small><br/>
    <small>email: <%= review.user.email %></small><br/>
    <hr>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for([@movie, @review]) do |f| %>
  <div>
    <%= f.label "text" %><br>
    <%= f.text_area "text", class: "form-control" %>
  </div>
  <div>
    <%= f.label "rating_out_of_ten" %><br>
    <%= f.number_field "rating_out_of_ten", class: "form-control" %>
  </div>
  <br>
  <div><%= f.submit "Submit", class: "btn btn-primary" %></div>
<% end %>

app/views/search/index.html.erb
<h1>Your Search Results:</h1>
<%= link_to "Back to Main", movies_path %>
<br>
<% @movies.each do |movie| %>
  <%= link_to image_tag(movie.poster), movie_path(movie) %>
  
  <h2><%= link_to movie.title, movie_path(movie) %></h2>
  
  <h3><%= formatted_date(movie.release_date) %></h3>
  
  <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
  
  <p><%= movie.description %></p>
  <hr>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for @user do |f| %>
  
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email", class: "form-control" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname", class: "form-control" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname", class: "form-control" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password", class: "form-control" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation", class: "form-control" %>
  </div>
  <br>
  <div><%= f.submit "Submit", class: "btn btn-primary"%></div>
<% end %>